//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public string RutA { get; set; }
        public string Nombre { get; set; }
        public string Carrera { get; set; }
        public string Jornada { get; set; }
        public int IDBicicleta { get; set; }
        public Nullable<int> IDBicicletaAnterior { get; set; }
        public Nullable<System.DateTime> HoraIngreso { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
        public string Comentario { get; set; }
    
        public virtual Bicicleta Bicicleta { get; set; }
    }
}
