//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class transit1_transitappEntities : DbContext
    {
        public transit1_transitappEntities()
            : base("name=transit1_transitappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrador> Administrador { get; set; }
        public DbSet<Alumno> Alumno { get; set; }
        public DbSet<Bicicleta> Bicicleta { get; set; }
        public DbSet<Guardia> Guardia { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Comentario> Comentario { get; set; }
    }
}
