//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransitApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bicicleta
    {
        public Bicicleta()
        {
            this.Alumno = new HashSet<Alumno>();
        }
    
        public int IDBicicleta { get; set; }
        public string Color { get; set; }
        public string Marca { get; set; }
        public string Imagen { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
    }
}
